CREATE DATABASE BIKE_SHARE;
USE BIKE_SHARE;

SELECT * FROM BIKE_0;

RENAME TABLE `BIKE_1` TO `BIKE_0`;
RENAME TABLE `BIKE_SHARE_1` TO `BIKE_1`;

-- Join both the table --

SELECT * FROM BIKE_0
UNION
SELECT * FROM BIKE_1;

-- Using CTE Join the table's

WITH CTE AS (
SELECT * FROM BIKE_0
UNION
SELECT * FROM BIKE_1
)
SELECT * FROM CTE c
LEFT JOIN COST_TABLE ct
ON C.YR = CT.YR;

WITH CTE AS (
SELECT * FROM BIKE_0
UNION 
SELECT * FROM BIKE_1
)
SELECT DTEDAY, SEASON, c.YR, `WEEKDAY`, HR, RIDER_TYPE, RIDERS, PRICE, COGS
FROM CTE c
LEFT JOIN COST_TABLE ct
ON c.YR = ct.YR;

-- Calculate the Profit & Revenue by using CTE -- 

WITH CTE AS (
SELECT * FROM BIKE_0
UNION 
SELECT * FROM BIKE_1
)
SELECT DTEDAY, SEASON, c.YR, `WEEKDAY`, HR, RIDER_TYPE, RIDERS, PRICE, COGS,
ROUND(RIDERS * PRICE,2) AS REVENUE, ROUND(RIDERS * PRICE - COGS,2) AS PROFIT
FROM CTE c
LEFT JOIN COST_TABLE ct
ON c.YR = ct.YR;

-- Time-based Usage Analysis --
-- 1. Calculate the total riders per year, season, and hour of day — identify peak usage patterns.

SELECT YR AS `YEAR`, SEASON, SUM(RIDERS) AS TOTAL_RIDERS, HR AS HOUR_OF_THE_DAY
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR, HR, SEASON
ORDER BY TOTAL_RIDERS;

-- IF WE WANT TO SEEK PEAK PARTTEN THEN 

WITH RANKED_USAGE AS (
SELECT YR AS `YEARS`, SEASON, SUM(RIDERS) AS TOTAL_RIDER, HR AS HOUR_OF_THE_DAY,
ROW_NUMBER() OVER (PARTITION BY YR ORDER BY SUM(RIDERS) DESC) AS RANKED
FROM (
SELECT * FROM BIKE_0
UNION ALL 
SELECT * FROM BIKE_1
) AS COMBINED 
GROUP BY YR, HR, SEASON
)
SELECT * FROM RANKED_USAGE
WHERE RANKED = 1;

-- 2. Find the top 3 busiest days each year in terms of rider count.

WITH DAILY_TOTAL AS (
SELECT YR AS `YEAR`, DTEDAY, SUM(RIDERS) AS TOTAL_RIDER
FROM(
SELECT * FROM BIKE_0
UNION ALL 
SELECT * FROM BIKE_1) AS COMBINED
GROUP BY YR, DTEDAY
),
RANKED_DAYS AS (
SELECT `YEAR`, DTEDAY, TOTAL_RIDER, 
RANK() OVER(PARTITION BY `YEAR` ORDER BY TOTAL_RIDER DESC) AS RANKED
FROM DAILY_TOTAL
) 
SELECT * FROM RANKED_DAYS
WHERE RANKED <=3
ORDER BY `YEAR`,TOTAL_RIDER DESC;

-- 3. Calculate the year-over-year growth in riders.

WITH YEARLY_TOTAL AS (
SELECT YR AS `YEAR`, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR
)
SELECT `YEAR`, TOTAL_RIDERS,
LAG(TOTAL_RIDERS) OVER(ORDER BY `YEAR`) AS PREVIOUS_YEAR_RIDERS,
ROUND(
(TOTAL_RIDERS - LAG(TOTAL_RIDERS) OVER(ORDER BY `YEAR`)) / LAG(TOTAL_RIDERS) OVER(ORDER BY `YEAR`) * 100, 2) AS YoY_GROWTH_PERCENTAGE 
FROM YEARLY_TOTAL
ORDER BY `YEAR`;
 
-- 4. Determine average riders during holidays vs. non-holidays.

SELECT HOLIDAY, AVG(RIDERS) AS AVG_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINE 
GROUP BY HOLIDAY;

-- 5. Compare weekday vs. weekend usage patterns

SELECT YR AS `YEAR`,
	CASE 
		WHEN WEEKDAY IN(0,6) THEN 'WEEKDAYS'
		ELSE 'WEEKEND'
	END AS DAY_TYPE,
SUM(RIDERS) AS TOTAL_RIDERS,    
ROUND(AVG(RIDERS),2) AS AVG_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR, DAY_TYPE
ORDER BY `YEAR`, DAY_TYPE;

-- 2. Rider Type & Weather Impact 

-- 1. Find the percentage contribution of each rider_type (casual/registered) per year.

SELECT YR AS `YEAR`, RIDER_TYPE, SUM(RIDERS) AS TOTAL_RIDERS,
ROUND((SUM(RIDERS) / SUM(SUM(RIDERS)) OVER(PARTITION BY YR)) * 100,2 ) AS PTC_CONTRIBUTE
FROM (
SELECT * FROM BIKE_0
UNION ALL 
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR, RIDER_TYPE
ORDER BY `YEAR`, TOTAL_RIDERS DESC;

-- 2. Analyze how weather conditions (weathersit) impact average riders.

SELECT WEATHERSIT,
CASE 
WHEN WEATHERSIT = 1 THEN 'CLEAR & PARTLY CLOUD'
WHEN WEATHERSIT = 2 THEN 'MIST & BROKEN CLOUD'
WHEN WEATHERSIT = 3 THEN 'LIGHT RAIN & THUNDERSTROM'
WHEN WEATHERSIT = 4 THEN 'HEAVY RAIN'
ELSE 'COOL WEATHER'
END AS WEATHER_DESCRIPTION,
ROUND(AVG(RIDERS),2) AS AVG_RIDERS, COUNT(*) AS TOTAL_HOURS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY WEATHERSIT
ORDER BY WEATHERSIT;

-- 3. Calculate the correlation between temperature (temp) and rider count (SQL approximation).

SELECT 
    (
        AVG(TEMP * RIDERS) - AVG(TEMP) * AVG(RIDERS)
    ) / 
    (SQRT(AVG(POW(TEMP, 2)) - POW(AVG(TEMP), 2)) * 
     SQRT(AVG(POW(RIDERS, 2)) - POW(AVG(RIDERS), 2))) 
    AS CORRELATION_TEMP_RIDERS
FROM (
    SELECT * FROM BIKE_0
    UNION ALL
    SELECT * FROM BIKE_1
) AS COMBINED;

-- 4. Compare average riders for days with workingday = 1 vs. workingday = 0.

SELECT WORKINGDAY, 
CASE 
WHEN WORKINGDAY = 1 THEN 'WORKING DAYS'
ELSE 'NON WORKING DAYS'
END AS DAY_TYPE,
ROUND(AVG(RIDERS),2) AS AVG_RIDERS, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY WORKINGDAY, DAY_TYPE
ORDER BY WORKINGDAY;

-- 3. Business-Usage Integration (JOIN with Dataset B)
-- 1. Join datasets on yr to calculate total revenue = riders × price.

SELECT b.YR AS `YEAR`, ROUND(SUM(b.RIDERS * ct.PRICE),2) AS TOTAL_REVENUE
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS b
JOIN COST_TABLE AS ct
ON ct.YR = b.YR
GROUP BY b.YR
ORDER BY b.YR;

-- 2. Calculate profit per year = (riders × price) − COGS.

SELECT b.YR AS `YEAR`, ROUND(SUM((b.RIDERS * ct.PRICE) - ct.COGS),2) AS PROFIT
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS b
JOIN COST_TABLE AS ct
ON b.YR = ct.YR
GROUP BY b.YR
ORDER BY b.YR;

-- 3. Find profit margin (%) per year.

SELECT b.YR AS `YEAR`, ROUND(SUM(b.RIDERS * ct.PRICE),2) AS TOTAL_REVENUE,
ROUND(SUM(b.RIDERS * ct.PRICE) - SUM(ct.COGS),2) AS TOTAL_PROFIT,
ROUND(SUM(b.RIDERS * ct.PRICE) - SUM(ct.COGS)/ SUM(b.RIDERS * ct.PRICE) * 100 ,2) AS PROFIT_MARGIN
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS b
JOIN COST_TABLE ct
ON b.YR = ct.YR
GROUP BY b.YR
ORDER BY b.YR;

-- 4.Determine the most profitable season by joining with business metrics.

SELECT b.SEASON,
	CASE 
    WHEN SEASON = 1 THEN 'WINTER'
    WHEN SEASON = 2 THEN 'SUMMER'
    WHEN SEASON = 3 THEN 'RAINY'
    WHEN SEASON = 4 THEN 'FALL'
    ELSE 'UNKOWN'
    END AS SEASON_NAME,
    ROUND(SUM(b.RIDERS * ct. PRICE),2) AS TOTAL_REVENUE,
    ROUND(SUM(b.RIDERS * ct.PRICE) - SUM(ct.COGS),2) AS TOTAL_PROFIT
    FROM (
    SELECT * FROM BIKE_0
    UNION ALL
    SELECT * FROM BIKE_1
    )AS b
    JOIN COST_TABLE ct
    ON b.YR = ct.YR
    GROUP BY b.SEASON
    ORDER BY b.SEASON;

-- 5.Identify years where rider growth > revenue growth.

WITH YEARLY_STAT AS (
SELECT b.YR AS `YEAR`, SUM(RIDERS) AS TOTAL_RIDERS,
 ROUND(SUM(b.RIDERS * ct. PRICE),2) AS TOTAL_REVENUE
	FROM (
    SELECT * FROM BIKE_0
    UNION ALL
    SELECT * FROM BIKE_1
    )AS b
JOIN COST_TABLE ct
    ON b.YR = ct.YR
    GROUP BY b.YR
), 
GROWTH_CALS AS(
SELECT `YEAR`, TOTAL_RIDERS, TOTAL_REVENUE,
ROUND(((TOTAL_RIDERS - LAG(TOTAL_RIDERS) OVER(ORDER BY `YEAR`)) / LAG(TOTAL_RIDERS) OVER(ORDER BY `YEAR`)) * 100,2) AS GROWTH_PCT_RIDERS,
ROUND(((TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER(ORDER BY `YEAR`)) / LAG(TOTAL_REVENUE) OVER(ORDER BY `YEAR`)) * 100,2) AS GROWTH_PCT_REVENUE
FROM YEARLY_STAT
)
SELECT `YEAR`, TOTAL_RIDERS, TOTAL_REVENUE, GROWTH_PCT_RIDERS, GROWTH_PCT_REVENUE
FROM GROWTH_CALS
WHERE GROWTH_PCT_RIDERS > GROWTH_PCT_REVENUE
ORDER BY `YEAR`;

-- 4. Advanced Aggregation & Ranking
-- 1. Use window functions to rank months by rider count within each year.

WITH MONTHS_RANKED AS(
SELECT YR AS `YEAR`, MNTH AS MONTHS, SUM(RIDERS) AS TOTAL_RIDERS 
FROM (
SELECT * FROM BIKE_0
UNION ALL 
SELECT * FROM BIKE_1) AS COMBINED
GROUP BY YR, MNTH
)
SELECT `YEAR`, MONTHS, TOTAL_RIDERS,
RANK() OVER(PARTITION BY `YEAR`, MONTHS ORDER BY TOTAL_RIDERS DESC) AS RANK_MNTH
FROM MONTHS_RANKED
ORDER BY `YEAR`, RANK_MNTH;

-- 2. Find the top 5 hours of the day across all years by rider volume.

WITH HOURLY_TOTALS AS (
SELECT HR AS HOURS, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
)AS COMBINE
GROUP BY HR
)
SELECT HOURS, TOTAL_RIDERS
FROM HOURLY_TOTALS
ORDER BY TOTAL_RIDERS DESC
LIMIT 5;

-- 3. For each year, identify the day with maximum riders and its weather condition.

WITH DAILY_TOTALS AS (
SELECT YR AS `YEAR`, DTEDAY, WEATHERSIT, SUM(RIDERS) AS TOTAL_RIDER, 
RANK() OVER(PARTITION BY YR ORDER BY SUM(RIDERS) DESC) AS RIDER_RANK
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR, DTEDAY, WEATHERSIT
)
SELECT `YEAR`, DTEDAY, WEATHERSIT, TOTAL_RIDER,
CASE 
WHEN WEATHERSIT = 1 THEN 'CLEARLY & PARTLY COLUD'
WHEN WEATHERSIT = 2 THEN 'MIST & BROKEN CLOUD'
WHEN WEATHERSIT = 3 THEN 'LIGHT RAIN & THUNDERSTROM'
WHEN WEATHERSIT = 4 THEN 'HEAVY RAIN'
ELSE 'UNKNOWN'
END AS WEATHER_CONDITION 
FROM DAILY_TOTALS
WHERE RIDER_RANK = 1
ORDER BY `YEAR`;

-- 4. Calculate a rolling average of daily riders for trend analysis.

WITH DAILY_RAIDERS AS (
SELECT DTEDAY, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_0
) AS COMBINED
GROUP BY DTEDAY
) 
SELECT DTEDAY, TOTAL_RIDERS, ROUND(AVG(TOTAL_RIDERS) OVER( ORDER BY DTEDAY ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),2) AS ROLLING_7DAY_AVG
FROM DAILY_RAIDERS
ORDER BY DTEDAY;

-- 5. Use lag/lead functions to compare riders with the previous hour/day.

WITH DAILY_RIDERS AS (
SELECT DTEDAY, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY DTEDAY
)
SELECT DTEDAY, TOTAL_RIDERS, LAG(TOTAL_RIDERS) OVER(ORDER BY DTEDAY) AS PREVIOUS_DAY_RIDERS,
TOTAL_RIDERS - LAG(TOTAL_RIDERS) OVER(ORDER BY DTEDAY) AS RIDER_DIFF_FROM_PREV_DAY
FROM DAILY_RIDERS
ORDER BY DTEDAY;

-- 5. Scenario-based Analysis
-- 1. Estimate the impact on profit if price increases by 10% without changing riders.

WITH MERGED AS(
SELECT b.YR, SUM(b.RIDERS) AS TOTAL_RIDER, ct.PRICE, ct.COGS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS b
JOIN COST_TABLE ct
ON b.YR = ct.YR
GROUP BY b.YR, ct.PRICE, ct.COGS
), 
PROFIT_CAL AS (
SELECT YR, TOTAL_RIDER, PRICE, COGS, TOTAL_RIDER - (PRICE * COGS) AS CURRENT_PROFIT,
(TOTAL_RIDER - (PRICE * 1.10) - COGS) AS NEW_PROFIT
FROM MERGED
)
SELECT YR, CURRENT_PROFIT, NEW_PROFIT, ROUND(NEW_PROFIT - CURRENT_PROFIT,2) AS PROFIT_CHANGE,
ROUND(((NEW_PROFIT - CURRENT_PROFIT) / NEW_PROFIT)*100,2) AS PCT_CHANGE
FROM PROFIT_CAL;

-- 2. Find how many days had riders above the yearly average.

WITH DAILY_TOTALS AS (
SELECT YR, DTEDAY, SUM(RIDERS) AS DAILY_RIDERS
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY YR, DTEDAY
), 
YEARLY_TOTALS AS(
SELECT YR, AVG(DAILY_RIDERS) AS AVG_RIDERS_YEARLY
FROM DAILY_TOTALS
GROUP BY YR
)
SELECT dT.YR, COUNT(*) AS DAY_ABOVE_AVG
FROM DAILY_TOTALS  dt
JOIN YEARLY_TOTALS yt
ON dt.YR = yt.YR
WHERE dt.DAILY_RIDERS > yt.AVG_RIDERS_YEARLY
GROUP BY dt.YR
ORDER BY dt.YR;

-- 3. Identify underperforming seasons (rider count below 25th percentile).

WITH DAILY_TOTALS AS(
SELECT SEASON, DTEDAY, SUM(RIDERS) AS DAILY_RIDER
FROM (
SELECT * FROM BIKE_0
UNION ALL
SELECT * FROM BIKE_1
) AS COMBINED
GROUP BY SEASON, DTEDAY
),
RANKED AS(
SELECT DISTINCT SEASON, DTEDAY, DAILY_RIDER,
ROW_NUMBER() OVER(PARTITION BY SEASON ORDER BY DAILY_RIDER) AS RN,
COUNT(*) OVER(PARTITION BY SEASON) AS TOTAL_DAYS
FROM DAILY_TOTALS
),
SEASONS_THRESHOLD AS(
SELECT SEASON, MIN(DAILY_RIDER) AS PCT_25_VALUE
FROM RANKED
WHERE RN >= FLOOR(0.25 * TOTAL_DAYS)
AND RN <= CEIL(0.25 * TOTAL_DAYS)
GROUP BY SEASON 
)
SELECT dt.SEASON, dt.DTEDAY, dt.DAILY_RIDER, st.PCT_25_VALUE AS SEASON_25TH_PERCENTILE
FROM DAILY_TOTALS dt
JOIN SEASONS_THRESHOLD st
ON dt.SEASON = st.SEASON
WHERE dt.DAILY_RIDER < st.PCT_25_VALUE
ORDER BY dt.DTEDAY, dt.SEASON;

-- 4. Calculate riders per $ of COGS as a cost efficiency metric.

SELECT b.YR AS `YEAR`, ROUND(SUM(b.RIDERS) / SUM(ct.COGS),2) AS RIDERS_PER_DOLLOR
FROM (
SELECT YR, DTEDAY, SUM(RIDERS) AS RIDERS
FROM ( 
SELECT YR, DTEDAY, RIDERS
FROM BIKE_0
UNION ALL
SELECT YR, DTEDAY, RIDERS
FROM BIKE_1
) AS COMBINED
GROUP BY YR, DTEDAY
) AS b
JOIN COST_TABLE ct
ON b.YR = ct.YR
GROUP BY b.YR
ORDER BY b.YR;

-- 5. Determine rider elasticity — % change in riders per % change in price (approximation)

WITH COMBINED_RIDER AS(
SELECT YR, SUM(RIDERS) AS TOTAL_RIDERS
FROM (
SELECT YR, RIDERS
FROM BIKE_0
UNION ALL
SELECT YR, RIDERS
FROM BIKE_1
) AS COMBINED 
GROUP BY YR
),
JOINED_DATA AS(
SELECT cr.YR, cr.TOTAL_RIDERS, ct.PRICE
FROM COMBINED_RIDER cr
JOIN COST_TABLE ct
ON cr.YR = ct.YR
),
CHANGES AS (
SELECT YR, TOTAL_RIDERS, PRICE
(TOTAL_RIDERS - LAG(TOTAL_RIDERS) OVER(ORDER BY YR)) / LAG(TOTAL_RIDERS) OVER(ORDER BY YR) * 100 AS PCT_CHANGE_RIDERS,
(PRICE - LAG(PRICE) OVER (ORDER BY YR)) / LAG(PRICE) OVER(ORDER BY YR) * 100 AS PCT_CHANGE_PRICE
FROM JOINED_DATA
)
SELECT YR, TOTAL_RIDERS, PRICE, PCT_CHANGE_RIDERS, PCT_CHANGE_PRICE,
CASE 
	WHEN PCT_CHANGE_PRICE != 0 THEN PCT_CHANGE_RIDERS / PCT_CHANGE_PRICE
    ELSE NULL
    END AS ELASTICITY
FROM CHANGES
ORDER BY YR;
